version: '3.3'

services:
    #service 1: definition of mysql database
    db:
      image: mysql:latest
      container_name: mysql-db2
      environment:
        - MYSQL_ROOT_PASSWORD=Svojas@123
        - MYSQL_USER=root
      ports:
        - "3307:3306"

    #service 2: definition of your spring-boot app
    student-enrollment:                     #it is just a name, which will be used only in this file.
      image: student-enrollment               #name of the image after dockerfile executes
      container_name: student-enrollment-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8084:8080"                       #docker container port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/enrollment?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Svojas@123